# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: my personal rocket science
email: webmaster@mypersonalrocketscience.de
description: > # this means to ignore newlines until "baseurl:"
  Some of the stuff here may be considered as rocket science by most of the people. I don't. I find it interesting...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.mypersonalrocketscience.de" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  myprs

# Build settings
markdown: kramdown
